version: "3.7"

services:
  traefik:
    image: traefik:v2.8
    restart: unless-stopped
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - dev-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/docker.sock:/var/run/docker.sock:ro
      - $PWD/data/traefik.yml:/traefik.yml:ro
      - $PWD/data/logs/:/data/logs:rw
      - $PWD/data/acme.json:/acme.json:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-network"
      - "traefik.http.middlewares.user-auth.basicauth.users=zhhnch:$$2y$$05$$/eHSBHUWLuhCKWhZn0ClcOJXH4f6cTvIuhQ/lD9V3yrQFMkY4SqUC"
      - "traefik.http.routers.traefik.middlewares=user-auth"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.rule=Host(`prostone.top`)"
      - "traefik.http.routers.traefik.service=api@internal"


networks:
  dev-network:
    external: true
