version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.9.18   
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=xhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - rabbit-network

networks:
  rabbit-network:
    name: rabbit-network
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "172.32.0.0/24"