version: "3.9"

services:
    
  consul:
    environment:
      - TZ=Asia/Shanghai
      - CONSUL_BIND_INTERFACE=eth0
    image: consul:1.12.2
    container_name: consul
    hostname: consul
    restart: always
    volumes:
      - /usr/local/share/consul/data:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    tty: true
    networks:
      - dev-network
    command:
      - agent
      - -server
      - -ui
      - -client=0.0.0.0
      - -bootstrap-expect=1
 
networks:
  dev-network:
    external: true
    

  