version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    volumes:
      - /usr/local/share/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - dev-server-net
 
networks:
  dev-server-net:
    external: true
    

  