version: '3.7'

services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    user: root
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper/data
    networks:
      - dev-network

  kafka:
    container_name: kafka
    hostname: kafka
    image: bitnami/kafka:3.1
    user: root
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      #定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL_LISTENER_CLIENTS:PLAINTEXT,INTERNAL_LISTENER_CLIENTS:PLAINTEXT,INTERNAL_LISTENER_BROKER:PLAINTEXT
      #定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=EXTERNAL_LISTENER_CLIENTS://0.0.0.0:9093,INTERNAL_LISTENER_CLIENTS://0.0.0.0:9094,INTERNAL_LISTENER_BROKER://0.0.0.0:9095
      #定义外网访问地址
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL_LISTENER_CLIENTS://192.168.31.9:9093,INTERNAL_LISTENER_BROKER://kafka:9095
      #定义broker通信协议
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_LISTENER_BROKER
      #定义zookeeper连接地址
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka/data
    depends_on:
      - zookeeper
    networks:
      - dev-network

volumes:
  kafka-data:
    name: kafka-data
    external: true
  zookeeper-data:
    name: zookeeper-data
    external: true

networks:
  dev-network:
    external: true

